#!/usr/bin/env python3
r"""Estimate the sensor offset by simulation, where the problem is well conditioned.

Three facts established so far:

1. The energy data term is **stationary** along a constant shift of
   :math:`\hat x_1`, so no first-order method travels that direction
   (``Docs/EPIBE.md`` §5).
2. The physics **does** identify the shift --- the cost of hiding an offset
   :math:`c` grows as :math:`c^2`, worth 6.8e-06 at the true bias
   (``scripts/location_coercivity.py``).
3. Reading that signal off a trained bank fails, because rebuilding the chain
   from :math:`\hat x_1` takes :math:`n` numerical derivatives and amplifies the
   decoder's high-frequency error to a floor of 1.9e-03 --- 280x the signal
   (``scripts/estimate_offset.py``).

Fact 3 is a conditioning problem, not an information problem, and it points at
its own fix: **stop differentiating and integrate instead.**  For a candidate
offset :math:`c`, fit the model to the measurement by *simulation*,

.. math:: \min_{x_0,\theta,a}\ \bigl\| x_1(t; x_0, \theta, a) - (y(t) - c) \bigr\|^2_{N,2},

and take the :math:`c` that minimizes it.  Every derivative is now taken by the
integrator on an exactly-known vector field rather than by finite differences on
a learned approximation, so the noise amplification of fact 3 disappears; the
model has no slack to hide the offset in, because the whole trajectory is
generated by the dynamics; and the residual is compared in the *output* space,
where the measurement noise sits, rather than after :math:`n` differentiations.

What this is and is not
-----------------------
This is not a replacement for the bank.  It estimates exactly one scalar --- the
quantity Eq. (54) is supposed to report and which the training objective is
provably blind to --- using eight unknowns per trajectory
(:math:`x_0 \in \mathbb{R}^3`, :math:`\theta \in \mathbb{R}^2`,
:math:`a \in \mathbb{R}^3`) on a short horizon.  It is the concrete form of the
anchor Proposition 1 requires and Remark 10 defers: cheap, well conditioned, and
independent of the degeneracy that defeats the data term.

Its output feeds the estimator as a corrected measurement :math:`y - \hat\mu`,
after which PIBE or EPIBE runs unchanged and unbiased.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

import torch  # noqa: E402

from pibe.basis import build_basis  # noqa: E402
from pibe.config import RunConfig  # noqa: E402
from pibe.data.disturbance import BasisDisturbance  # noqa: E402
from pibe.experiment import build_experiment  # noqa: E402
from pibe.utils.logging import setup_logging  # noqa: E402


def box(raw: torch.Tensor, lo: torch.Tensor, hi: torch.Tensor) -> torch.Tensor:
    """Keep a parameter inside its admissible interval, smoothly."""
    return lo + (hi - lo) * torch.sigmoid(raw)


def integrate(system, basis, t_grid, x0, theta, a, substeps: int) -> torch.Tensor:
    """Differentiable RK4 over the data grid.

    :func:`pibe.data.simulate.rk4_integrate` is deliberately wrapped in
    ``no_grad`` --- it generates ground truth, and a graph through it would be a
    bug --- so shooting needs its own copy.  This one is identical in scheme and
    carries gradients back to ``x0``, ``theta`` and ``a``.
    """
    disturbance = BasisDisturbance(basis, a)
    x = x0
    states = [x]
    for k in range(t_grid.numel() - 1):
        h = (t_grid[k + 1] - t_grid[k]) / substeps
        t = t_grid[k]
        for _ in range(substeps):
            def field(time, state):
                return system.vector_field(state, theta, disturbance(time))

            k1 = field(t, x)
            k2 = field(t + 0.5 * h, x + 0.5 * h * k1)
            k3 = field(t + 0.5 * h, x + 0.5 * h * k2)
            k4 = field(t + h, x + h * k3)
            x = x + (h / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
            t = t + h
        states.append(x)
    return torch.stack(states, dim=-2)


def fit_jointly(
    system, basis, t_grid, y, x0_bounds, theta_bounds, coeff_bounds,
    offset_bound: float, steps: int, lr: float, substeps: int, seed: int,
    report_every: int = 0,
):
    r"""Fit :math:`(x_0, \theta, a, \mu)` to :math:`y` by simulation.

    The offset is a *parameter* here rather than something scanned, and it can
    be, because the degeneracy that makes it unrecoverable inside the bank is
    absent: there, :math:`\hat x^k_k` is free and absorbs any shift of
    :math:`\hat x^k_{k-1}`, whereas here the entire trajectory is generated by
    the dynamics from eight numbers and has no slack to hide a shift in.  The
    quantity being fitted is :math:`x_1(t) + \mu \approx y(t)`, so
    :math:`\hat\mu` is exactly the sensor offset Eq. (54) is meant to report.
    """
    count = y.shape[0]
    generator = torch.Generator().manual_seed(seed)

    raw_x0 = torch.zeros(count, system.n, dtype=y.dtype)
    raw_x0 += 0.1 * torch.randn(raw_x0.shape, generator=generator, dtype=y.dtype)
    raw_x0.requires_grad_(True)
    raw_theta = torch.zeros(system.theta_dim, dtype=y.dtype, requires_grad=True)
    raw_a = torch.zeros(count, basis.q, dtype=y.dtype, requires_grad=True)
    mu = torch.zeros((), dtype=y.dtype, requires_grad=True)

    optimizer = torch.optim.Adam(
        [{"params": [raw_x0, raw_theta, raw_a], "lr": lr},
         {"params": [mu], "lr": lr * 0.2}]
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=steps)

    for step in range(steps):
        optimizer.zero_grad(set_to_none=True)
        x0 = box(raw_x0, x0_bounds[:, 0], x0_bounds[:, 1])
        theta = box(raw_theta, theta_bounds[:, 0], theta_bounds[:, 1])
        a = box(raw_a, coeff_bounds[:, 0], coeff_bounds[:, 1])
        simulated = integrate(
            system, basis, t_grid, x0,
            theta.reshape(1, -1).expand(count, -1), a, substeps,
        )
        cost = torch.mean((simulated[..., 0] + mu - y) ** 2)
        cost.backward()
        optimizer.step()
        scheduler.step()
        with torch.no_grad():
            mu.clamp_(-offset_bound, offset_bound)
        if report_every and step % report_every == 0:
            print(f"    step {step:>5} | cost {float(cost):.4e} | "
                  f"mu {float(mu):+.5f} | theta "
                  f"[{float(theta[0]):+.4f}, {float(theta[1]):+.4f}]", flush=True)

    with torch.no_grad():
        theta = box(raw_theta, theta_bounds[:, 0], theta_bounds[:, 1])
    return float(cost), float(mu), theta.detach()


def fit_at_offset(
    system, basis, t_grid, target, x0_bounds, theta_bounds, coeff_bounds,
    steps: int, lr: float, substeps: int, seed: int,
) -> tuple[float, torch.Tensor, torch.Tensor]:
    r"""Best simulated fit to ``target``; returns ``(cost, theta, a)``.

    ``target`` is :math:`y - c`, shape ``(P, N)``.  Each trajectory gets its own
    initial condition and disturbance coefficients; the parameters are shared,
    since :math:`\theta` is a property of the plant rather than of a trajectory.
    """
    count = target.shape[0]
    generator = torch.Generator().manual_seed(seed)

    raw_x0 = torch.zeros(count, system.n, dtype=target.dtype, requires_grad=True)
    raw_theta = torch.zeros(system.theta_dim, dtype=target.dtype, requires_grad=True)
    raw_a = torch.zeros(count, basis.q, dtype=target.dtype, requires_grad=True)
    with torch.no_grad():
        raw_x0 += 0.1 * torch.randn(raw_x0.shape, generator=generator, dtype=target.dtype)

    optimizer = torch.optim.Adam([raw_x0, raw_theta, raw_a], lr=lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=steps)

    for _ in range(steps):
        optimizer.zero_grad(set_to_none=True)
        x0 = box(raw_x0, x0_bounds[:, 0], x0_bounds[:, 1])
        theta = box(raw_theta, theta_bounds[:, 0], theta_bounds[:, 1])
        a = box(raw_a, coeff_bounds[:, 0], coeff_bounds[:, 1])
        simulated = integrate(
            system, basis, t_grid, x0,
            theta.reshape(1, -1).expand(count, -1), a, substeps,
        )
        cost = torch.mean((simulated[..., 0] - target) ** 2)
        cost.backward()
        optimizer.step()
        scheduler.step()

    with torch.no_grad():
        x0 = box(raw_x0, x0_bounds[:, 0], x0_bounds[:, 1])
        theta = box(raw_theta, theta_bounds[:, 0], theta_bounds[:, 1])
        a = box(raw_a, coeff_bounds[:, 0], coeff_bounds[:, 1])
        simulated = integrate(
            system, basis, t_grid, x0,
            theta.reshape(1, -1).expand(count, -1), a, substeps,
        )
        cost = float(torch.mean((simulated[..., 0] - target) ** 2))
    return cost, theta.detach(), a.detach()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--offsets", type=float, nargs="+", default=None)
    parser.add_argument("--trajectories", type=int, default=4)
    parser.add_argument("--steps", type=int, default=1500)
    parser.add_argument("--lr", type=float, default=0.05)
    parser.add_argument("--substeps", type=int, default=2)
    parser.add_argument(
        "--window", type=int, default=101,
        help="samples used from the start of each trajectory. The offset is a\n             constant, so a short window identifies it and keeps the\n             backward pass through the integrator affordable.",
    )
    parser.add_argument("--offset-bound", type=float, default=0.3)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()
    setup_logging("WARNING")

    config = RunConfig.from_yaml(args.config)
    experiment = build_experiment(config)
    system, basis = experiment.system, experiment.basis
    true_bias = config.data.noise_bias

    data = experiment.val_data
    count = min(args.trajectories, len(data))
    window = min(args.window, data.n_samples)
    y = data.y[:count, :window].cpu()
    t_grid = data.t[:window].cpu()
    coeff_bounds = experiment.coefficient_bounds.cpu()

    print(f"fitting (x0, theta, a, mu) to y by simulation on {count} trajectory/ies, "
          f"{window} samples\n")
    cost, mu_hat, theta = fit_jointly(
        system, basis, t_grid, y, system.x0_bounds, system.theta_bounds,
        coeff_bounds, args.offset_bound, args.steps, args.lr, args.substeps,
        args.seed, report_every=max(1, args.steps // 10),
    )
    floor = getattr(experiment.noise, "variance", None)
    rows = [{"cost": cost, "mu_hat": mu_hat, "theta": theta.tolist()}]
    best = {"offset": mu_hat, "cost": cost, "theta": theta.tolist()}
    print()
    print(f"estimated sensor offset  mu_hat = {mu_hat:+.5f}")
    print(f"true sensor offset               = {true_bias:+.5f}")
    if floor is not None:
        print(f"residual {cost:.4e}  vs noise variance {floor:.4e}  "
              f"(ratio {cost/floor:.2f}; 1.0 means the fit is at the noise floor)")
    print(f"theta_hat = {[round(float(v), 4) for v in theta]}   "
          f"true = {[round(float(v), 4) for v in data.theta[0]]}")

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(
            {"rows": rows, "mu_hat": best["offset"], "true_bias": true_bias,
             "theta_at_min": best["theta"]}, indent=2))
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
